/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ProfileInfo {
  'bio' : string,
  'title' : string,
  'name' : string,
  'office' : string,
  'photoUrl' : string,
  'email' : string,
  'affiliation' : string,
}
export interface Publication {
  'doi' : string,
  'title' : string,
  'venue' : string,
  'year' : bigint,
  'authors' : string,
  'pdfUrl' : string,
  'abstract' : string,
}
export interface ResearchInterest { 'title' : string, 'description' : string }
export interface SocialLinks {
  'linkedIn' : string,
  'cvUrl' : string,
  'googleScholar' : string,
  'github' : string,
}
export interface TeachingExperience {
  'semester' : string,
  'role' : string,
  'year' : bigint,
  'courseCode' : string,
  'courseName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdatePublication' : ActorMethod<[Publication], undefined>,
  'addOrUpdateResearchInterest' : ActorMethod<[ResearchInterest], undefined>,
  'addOrUpdateTeachingExperience' : ActorMethod<
    [TeachingExperience],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfileInfo' : ActorMethod<[], ProfileInfo>,
  'getPublications' : ActorMethod<[], Array<Publication>>,
  'getResearchInterests' : ActorMethod<[], Array<ResearchInterest>>,
  'getSocialLinks' : ActorMethod<[], SocialLinks>,
  'getTeachingExperience' : ActorMethod<[], Array<TeachingExperience>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removePublication' : ActorMethod<[string], undefined>,
  'removeResearchInterest' : ActorMethod<[string], undefined>,
  'removeTeachingExperience' : ActorMethod<[string], undefined>,
  'updateProfileInfo' : ActorMethod<[ProfileInfo], undefined>,
  'updateSocialLinks' : ActorMethod<[SocialLinks], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];