/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Publication = IDL.Record({
  'doi' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'year' : IDL.Nat,
  'authors' : IDL.Text,
  'pdfUrl' : IDL.Text,
  'abstract' : IDL.Text,
});
export const ResearchInterest = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const TeachingExperience = IDL.Record({
  'semester' : IDL.Text,
  'role' : IDL.Text,
  'year' : IDL.Nat,
  'courseCode' : IDL.Text,
  'courseName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfileInfo = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'office' : IDL.Text,
  'photoUrl' : IDL.Text,
  'email' : IDL.Text,
  'affiliation' : IDL.Text,
});
export const SocialLinks = IDL.Record({
  'linkedIn' : IDL.Text,
  'cvUrl' : IDL.Text,
  'googleScholar' : IDL.Text,
  'github' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdatePublication' : IDL.Func([Publication], [], []),
  'addOrUpdateResearchInterest' : IDL.Func([ResearchInterest], [], []),
  'addOrUpdateTeachingExperience' : IDL.Func([TeachingExperience], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfileInfo' : IDL.Func([], [ProfileInfo], ['query']),
  'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getResearchInterests' : IDL.Func([], [IDL.Vec(ResearchInterest)], ['query']),
  'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
  'getTeachingExperience' : IDL.Func(
      [],
      [IDL.Vec(TeachingExperience)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removePublication' : IDL.Func([IDL.Text], [], []),
  'removeResearchInterest' : IDL.Func([IDL.Text], [], []),
  'removeTeachingExperience' : IDL.Func([IDL.Text], [], []),
  'updateProfileInfo' : IDL.Func([ProfileInfo], [], []),
  'updateSocialLinks' : IDL.Func([SocialLinks], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Publication = IDL.Record({
    'doi' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'year' : IDL.Nat,
    'authors' : IDL.Text,
    'pdfUrl' : IDL.Text,
    'abstract' : IDL.Text,
  });
  const ResearchInterest = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const TeachingExperience = IDL.Record({
    'semester' : IDL.Text,
    'role' : IDL.Text,
    'year' : IDL.Nat,
    'courseCode' : IDL.Text,
    'courseName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfileInfo = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'office' : IDL.Text,
    'photoUrl' : IDL.Text,
    'email' : IDL.Text,
    'affiliation' : IDL.Text,
  });
  const SocialLinks = IDL.Record({
    'linkedIn' : IDL.Text,
    'cvUrl' : IDL.Text,
    'googleScholar' : IDL.Text,
    'github' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdatePublication' : IDL.Func([Publication], [], []),
    'addOrUpdateResearchInterest' : IDL.Func([ResearchInterest], [], []),
    'addOrUpdateTeachingExperience' : IDL.Func([TeachingExperience], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfileInfo' : IDL.Func([], [ProfileInfo], ['query']),
    'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getResearchInterests' : IDL.Func(
        [],
        [IDL.Vec(ResearchInterest)],
        ['query'],
      ),
    'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
    'getTeachingExperience' : IDL.Func(
        [],
        [IDL.Vec(TeachingExperience)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removePublication' : IDL.Func([IDL.Text], [], []),
    'removeResearchInterest' : IDL.Func([IDL.Text], [], []),
    'removeTeachingExperience' : IDL.Func([IDL.Text], [], []),
    'updateProfileInfo' : IDL.Func([ProfileInfo], [], []),
    'updateSocialLinks' : IDL.Func([SocialLinks], [], []),
  });
};

export const init = ({ IDL }) => { return []; };